/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui.quickfix;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class MathQuickfixProvider /* implements DefaultQuickfixProvider  */{
}
