/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation;

import dk.sdu.mmmi.mdsd.math.VarBinding;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MathValidator extends AbstractMathValidator {
  public static final String VAR_UNIQUE = "var_unique";
  
  /* @Check
   */public void uniqueGlobalVariableDefinition(final VarBinding binding) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field variables is undefined for the type MathExp"
      + "\nThe method or field eContainer is undefined for the type VarBinding"
      + "\nThe method or field name is undefined"
      + "\nThe method error(String, Object, String) is undefined"
      + "\nThe method or field binding_Name is undefined for the type MathPackage"
      + "\nfilter cannot be resolved"
      + "\n== cannot be resolved"
      + "\nsize cannot be resolved"
      + "\n> cannot be resolved");
  }
}
