/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui.labeling;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class MathDescriptionLabelProvider /* implements DefaultDescriptionLabelProvider  */{
}
