/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui.labeling;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
@SuppressWarnings("all")
public class MathLabelProvider /* implements DefaultEObjectLabelProvider  */{
  /* @Inject
   */public MathLabelProvider(final /* AdapterFactoryLabelProvider */Object delegate) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AdapterFactoryLabelProvider) is undefined");
  }
}
