/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class MathUiModule extends AbstractMathUiModule {
}
